/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalNovaCredits' : bigint,
  'totalUsers' : bigint,
  'totalLoginsToday' : bigint,
  'totalDonations' : bigint,
  'pendingPurchases' : bigint,
}
export interface ConquestLeaderboardEntry {
  'principal' : Principal,
  'timestamp' : Time,
  'planetsOwned' : bigint,
}
export interface Donation {
  'message' : string,
  'timestamp' : Time,
  'amount' : bigint,
  'donor' : Principal,
}
export interface DonorAggregate {
  'principal' : Principal,
  'totalAmount' : bigint,
}
export interface GameLeaderboardEntry {
  'principal' : Principal,
  'totalGameCredits' : bigint,
}
export interface LoginRecord { 'user' : Principal, 'timestamp' : Time }
export interface NFTWaitlistEntry {
  'name' : string,
  'user' : Principal,
  'walletAddress' : string,
  'timestamp' : Time,
}
export interface Planet {
  'planetName' : string,
  'owner' : Principal,
  'claimedAt' : Time,
}
export interface PlanetJournal {
  'planetName' : string,
  'entry' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface PurchaseRequest {
  'id' : bigint,
  'status' : PurchaseRequestStatus,
  'cryptoType' : string,
  'transactionHash' : string,
  'user' : Principal,
  'timestamp' : Time,
  'creditsRequested' : bigint,
}
export type PurchaseRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Star {
  'owner' : Principal,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'favoritePlanet' : [] | [string],
  'name' : string,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePurchaseRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], undefined>,
  'claimPlanet' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'earnCredits' : ActorMethod<[bigint, string], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllPlanets' : ActorMethod<[], Array<Planet>>,
  'getAllPurchaseRequests' : ActorMethod<[], Array<PurchaseRequest>>,
  'getAllStars' : ActorMethod<[], Array<Star>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConquestLeaderboard' : ActorMethod<[], Array<ConquestLeaderboardEntry>>,
  'getDonations' : ActorMethod<[], Array<Donation>>,
  'getGameLeaderboard' : ActorMethod<[], Array<GameLeaderboardEntry>>,
  'getJournalEntriesForPlanet' : ActorMethod<[string], Array<PlanetJournal>>,
  'getLoginActivity' : ActorMethod<[], Array<LoginRecord>>,
  'getNFTWaitlist' : ActorMethod<[], Array<NFTWaitlistEntry>>,
  'getStarsByOwner' : ActorMethod<[Principal], Array<Star>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTodayLoginCount' : ActorMethod<[], bigint>,
  'getTopDonors' : ActorMethod<[], Array<DonorAggregate>>,
  'getTotalDonations' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPurchaseRequests' : ActorMethod<[], Array<PurchaseRequest>>,
  'getWeeklyConquestWinner' : ActorMethod<[], Principal>,
  'hasAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPremiumUser' : ActorMethod<[Principal], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordDonation' : ActorMethod<[bigint, string], undefined>,
  'recordGameCreditsEarned' : ActorMethod<[bigint], undefined>,
  'recordLogin' : ActorMethod<[], undefined>,
  'rejectPurchaseRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'spendCredits' : ActorMethod<[bigint], boolean>,
  'submitJournalEntry' : ActorMethod<[string, string], undefined>,
  'submitNFTWaitlist' : ActorMethod<[string, string], undefined>,
  'submitPurchaseRequest' : ActorMethod<[string, string, bigint], undefined>,
  'submitStar' : ActorMethod<[string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];