/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalNovaCredits' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalLoginsToday' : IDL.Nat,
  'totalDonations' : IDL.Nat,
  'pendingPurchases' : IDL.Nat,
});
export const Time = IDL.Int;
export const Star = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'favoritePlanet' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
});
export const Donation = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'donor' : IDL.Principal,
});
export const PlanetJournal = IDL.Record({
  'planetName' : IDL.Text,
  'entry' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const LoginRecord = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : Time,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const DonorAggregate = IDL.Record({
  'principal' : IDL.Principal,
  'totalAmount' : IDL.Nat,
});
export const PurchaseRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PurchaseRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PurchaseRequestStatus,
  'cryptoType' : IDL.Text,
  'transactionHash' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'creditsRequested' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePurchaseRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'earnCredits' : IDL.Func([IDL.Nat], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllStars' : IDL.Func([], [IDL.Vec(Star)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getJournalEntriesForPlanet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlanetJournal)],
      ['query'],
    ),
  'getLoginActivity' : IDL.Func([], [IDL.Vec(LoginRecord)], ['query']),
  'getStarsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Star)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTodayLoginCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTopDonors' : IDL.Func([], [IDL.Vec(DonorAggregate)], ['query']),
  'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserPurchaseRequests' : IDL.Func(
      [],
      [IDL.Vec(PurchaseRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPremiumUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordDonation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'recordLogin' : IDL.Func([], [], []),
  'rejectPurchaseRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'spendCredits' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitPurchaseRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'submitStar' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalNovaCredits' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalLoginsToday' : IDL.Nat,
    'totalDonations' : IDL.Nat,
    'pendingPurchases' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Star = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'favoritePlanet' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
  });
  const Donation = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'donor' : IDL.Principal,
  });
  const PlanetJournal = IDL.Record({
    'planetName' : IDL.Text,
    'entry' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const LoginRecord = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : Time,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const DonorAggregate = IDL.Record({
    'principal' : IDL.Principal,
    'totalAmount' : IDL.Nat,
  });
  const PurchaseRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PurchaseRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PurchaseRequestStatus,
    'cryptoType' : IDL.Text,
    'transactionHash' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'creditsRequested' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePurchaseRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'earnCredits' : IDL.Func([IDL.Nat], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllStars' : IDL.Func([], [IDL.Vec(Star)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getJournalEntriesForPlanet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlanetJournal)],
        ['query'],
      ),
    'getLoginActivity' : IDL.Func([], [IDL.Vec(LoginRecord)], ['query']),
    'getStarsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Star)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTodayLoginCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTopDonors' : IDL.Func([], [IDL.Vec(DonorAggregate)], ['query']),
    'getTotalDonations' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserPurchaseRequests' : IDL.Func(
        [],
        [IDL.Vec(PurchaseRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPremiumUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordDonation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'recordLogin' : IDL.Func([], [], []),
    'rejectPurchaseRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'spendCredits' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitPurchaseRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'submitStar' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };